services:
  db:
    image: postgres:17.0-bookworm
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=finance_config
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  django:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    container_name: django
    command: ./docker/web_entrypoint.sh
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/finance_config
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure

