services:

  db:
    image: postgres:17.0-bookworm
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=finance_config
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
    postgres-data:
    redis-data:

